### ISSUE TITLE
na_configuration should explicitly enable or disable averaging

### ISSUE THREAD

**Issue by raphaelcervantes** [axiondarkmatterexperiment/dripline-orpheus#26]

**Comment by parasharmohapatra** [comment]
@raphaelcervantes what do you mean by this? 
I am interpreting this as having a variable called average_enable in motor_control.py. If that is true then average = xx will be set. if its False average = 0 will be set. Is that correct?

**Comment by raphaelcervantes** [comment]
No. You need to send a SCPI command to explicitly enable averaging. See my comment on your pull request.
