### ISSUE TITLE
log na_measurement_status_explanation

### ISSUE THREAD

**Issue by parasharmohapatra** [axiondarkmatterexperiment/dripline-orpheus#32]
@raphaelcervantes Currently, modemap_measurement_status_explanation only logs when there is a description provided. Should we log empty strings for consistency?

**Comment by raphaelcervantes** [comment]
I thought I set the default to an empty string. We could log empty strings. But I also don't see anything wrong with leaving it as a null value, as long as the data-processing scripts can handle it.

**Comment by parasharmohapatra** [comment]
@raphaelcervantes 
```
if not modemap_notes == None:
            self.cmd_interface.set('modemap_measurement_status_explanation', modemap_notes)
```
you didn't. I can add that. the queries might be faster if we add it. I also like the idea of logging it anyway just for consistency. But, its up to you.

**Comment by raphaelcervantes** [comment]
@parashar2399 closing now.
