### ISSUE TITLE
Make sure VNA source is on before performing transmission and reflection measurement

### ISSUE THREAD

**Issue by raphaelcervantes** [axiondarkmatterexperiment/dripline-orpheus#48]
https://github.com/axiondarkmatterexperiment/dripline-orpheus/blob/b2a4381477bd115515bba07cb11da57fa9470163/data_taking_scripts/data_logging.py#L90

https://github.com/axiondarkmatterexperiment/dripline-orpheus/blob/b2a4381477bd115515bba07cb11da57fa9470163/data_taking_scripts/data_logging.py#L136

The measurement is rubbish if the VNA isn't on.

**Comment by jtsinnis** [comment]
na_output is now turned on at the start of these three functions (log_reflection_switches, log_transmission_switches, log_transmission_reflection_switches)
